# Generated by Django 5.2.3 on 2025-06-28 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
